name: Deploy Frontend to S3

on:
  push:
    branches:
      - main   # Deploy on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to S3
        uses: aws-actions/s3-sync@v2
        with:
          source_dir: dist/  # Change to dist/ if your framework uses that
          bucket: ${{ secrets.AWS_S3_BUCKET }}
          region: ${{ secrets.AWS_REGION }}
          delete: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}   